/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.parser;

import sarapatel.node.*;
import sarapatel.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNumeroInt(@SuppressWarnings("unused") TNumeroInt node)
    {
        this.index = 0;
    }

    @Override
    public void caseTNumeroReal(@SuppressWarnings("unused") TNumeroReal node)
    {
        this.index = 1;
    }

    @Override
    public void caseTNumeroBinario(@SuppressWarnings("unused") TNumeroBinario node)
    {
        this.index = 2;
    }

    @Override
    public void caseTDeclVar(@SuppressWarnings("unused") TDeclVar node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDeclConst(@SuppressWarnings("unused") TDeclConst node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDeclProcedimento(@SuppressWarnings("unused") TDeclProcedimento node)
    {
        this.index = 5;
    }

    @Override
    public void caseTDeclFuncao(@SuppressWarnings("unused") TDeclFuncao node)
    {
        this.index = 6;
    }

    @Override
    public void caseTCmdSe(@SuppressWarnings("unused") TCmdSe node)
    {
        this.index = 7;
    }

    @Override
    public void caseTCmdSenao(@SuppressWarnings("unused") TCmdSenao node)
    {
        this.index = 8;
    }

    @Override
    public void caseTCmdEnquanto(@SuppressWarnings("unused") TCmdEnquanto node)
    {
        this.index = 9;
    }

    @Override
    public void caseTTipoInteiro(@SuppressWarnings("unused") TTipoInteiro node)
    {
        this.index = 10;
    }

    @Override
    public void caseTTipoBooleano(@SuppressWarnings("unused") TTipoBooleano node)
    {
        this.index = 11;
    }

    @Override
    public void caseTTipoReal(@SuppressWarnings("unused") TTipoReal node)
    {
        this.index = 12;
    }

    @Override
    public void caseTTipoCadeia(@SuppressWarnings("unused") TTipoCadeia node)
    {
        this.index = 13;
    }

    @Override
    public void caseTInicioBloco(@SuppressWarnings("unused") TInicioBloco node)
    {
        this.index = 14;
    }

    @Override
    public void caseTFimBloco(@SuppressWarnings("unused") TFimBloco node)
    {
        this.index = 15;
    }

    @Override
    public void caseTParEsq(@SuppressWarnings("unused") TParEsq node)
    {
        this.index = 16;
    }

    @Override
    public void caseTParDir(@SuppressWarnings("unused") TParDir node)
    {
        this.index = 17;
    }

    @Override
    public void caseTColEsq(@SuppressWarnings("unused") TColEsq node)
    {
        this.index = 18;
    }

    @Override
    public void caseTColDir(@SuppressWarnings("unused") TColDir node)
    {
        this.index = 19;
    }

    @Override
    public void caseTAbreComentario(@SuppressWarnings("unused") TAbreComentario node)
    {
        this.index = 20;
    }

    @Override
    public void caseTFechaComentario(@SuppressWarnings("unused") TFechaComentario node)
    {
        this.index = 21;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 22;
    }

    @Override
    public void caseTPartida(@SuppressWarnings("unused") TPartida node)
    {
        this.index = 23;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 24;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 25;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 26;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 27;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 28;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 29;
    }

    @Override
    public void caseTNegacao(@SuppressWarnings("unused") TNegacao node)
    {
        this.index = 30;
    }

    @Override
    public void caseTCompE(@SuppressWarnings("unused") TCompE node)
    {
        this.index = 31;
    }

    @Override
    public void caseTCompOu(@SuppressWarnings("unused") TCompOu node)
    {
        this.index = 32;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 33;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 34;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 35;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 36;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 37;
    }

    @Override
    public void caseTVerdade(@SuppressWarnings("unused") TVerdade node)
    {
        this.index = 38;
    }

    @Override
    public void caseTFalso(@SuppressWarnings("unused") TFalso node)
    {
        this.index = 39;
    }

    @Override
    public void caseTCadeia(@SuppressWarnings("unused") TCadeia node)
    {
        this.index = 40;
    }

    @Override
    public void caseTComentarioLinha(@SuppressWarnings("unused") TComentarioLinha node)
    {
        this.index = 41;
    }

    @Override
    public void caseTComentarioBloco(@SuppressWarnings("unused") TComentarioBloco node)
    {
        this.index = 42;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 43;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 44;
    }
}
