/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoExpressoesBlocoExpressoes extends PBlocoExpressoes
{
    private TInicioBloco _inicioBloco_;
    private final LinkedList<PProdDeclConst> _prodDeclConst_ = new LinkedList<PProdDeclConst>();
    private PTernarioExp _ternarioExp_;
    private TFimBloco _fimBloco_;

    public ABlocoExpressoesBlocoExpressoes()
    {
        // Constructor
    }

    public ABlocoExpressoesBlocoExpressoes(
        @SuppressWarnings("hiding") TInicioBloco _inicioBloco_,
        @SuppressWarnings("hiding") List<?> _prodDeclConst_,
        @SuppressWarnings("hiding") PTernarioExp _ternarioExp_,
        @SuppressWarnings("hiding") TFimBloco _fimBloco_)
    {
        // Constructor
        setInicioBloco(_inicioBloco_);

        setProdDeclConst(_prodDeclConst_);

        setTernarioExp(_ternarioExp_);

        setFimBloco(_fimBloco_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoExpressoesBlocoExpressoes(
            cloneNode(this._inicioBloco_),
            cloneList(this._prodDeclConst_),
            cloneNode(this._ternarioExp_),
            cloneNode(this._fimBloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExpressoesBlocoExpressoes(this);
    }

    public TInicioBloco getInicioBloco()
    {
        return this._inicioBloco_;
    }

    public void setInicioBloco(TInicioBloco node)
    {
        if(this._inicioBloco_ != null)
        {
            this._inicioBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicioBloco_ = node;
    }

    public LinkedList<PProdDeclConst> getProdDeclConst()
    {
        return this._prodDeclConst_;
    }

    public void setProdDeclConst(List<?> list)
    {
        for(PProdDeclConst e : this._prodDeclConst_)
        {
            e.parent(null);
        }
        this._prodDeclConst_.clear();

        for(Object obj_e : list)
        {
            PProdDeclConst e = (PProdDeclConst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._prodDeclConst_.add(e);
        }
    }

    public PTernarioExp getTernarioExp()
    {
        return this._ternarioExp_;
    }

    public void setTernarioExp(PTernarioExp node)
    {
        if(this._ternarioExp_ != null)
        {
            this._ternarioExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ternarioExp_ = node;
    }

    public TFimBloco getFimBloco()
    {
        return this._fimBloco_;
    }

    public void setFimBloco(TFimBloco node)
    {
        if(this._fimBloco_ != null)
        {
            this._fimBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimBloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inicioBloco_)
            + toString(this._prodDeclConst_)
            + toString(this._ternarioExp_)
            + toString(this._fimBloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inicioBloco_ == child)
        {
            this._inicioBloco_ = null;
            return;
        }

        if(this._prodDeclConst_.remove(child))
        {
            return;
        }

        if(this._ternarioExp_ == child)
        {
            this._ternarioExp_ = null;
            return;
        }

        if(this._fimBloco_ == child)
        {
            this._fimBloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inicioBloco_ == oldChild)
        {
            setInicioBloco((TInicioBloco) newChild);
            return;
        }

        for(ListIterator<PProdDeclConst> i = this._prodDeclConst_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PProdDeclConst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._ternarioExp_ == oldChild)
        {
            setTernarioExp((PTernarioExp) newChild);
            return;
        }

        if(this._fimBloco_ == oldChild)
        {
            setFimBloco((TFimBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
