/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AComandoSeSenaoCasadoComandoSeCasado extends PComandoSeCasado
{
    private TCmdSe _cmdSe_;
    private TParEsq _parEsq_;
    private PTernarioExp _ternarioExp_;
    private TParDir _parDir_;
    private PComandoSeCasado _comandoSe_;
    private TCmdSenao _cmdSenao_;
    private PComandoSeCasado _comandoSenao_;

    public AComandoSeSenaoCasadoComandoSeCasado()
    {
        // Constructor
    }

    public AComandoSeSenaoCasadoComandoSeCasado(
        @SuppressWarnings("hiding") TCmdSe _cmdSe_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PTernarioExp _ternarioExp_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PComandoSeCasado _comandoSe_,
        @SuppressWarnings("hiding") TCmdSenao _cmdSenao_,
        @SuppressWarnings("hiding") PComandoSeCasado _comandoSenao_)
    {
        // Constructor
        setCmdSe(_cmdSe_);

        setParEsq(_parEsq_);

        setTernarioExp(_ternarioExp_);

        setParDir(_parDir_);

        setComandoSe(_comandoSe_);

        setCmdSenao(_cmdSenao_);

        setComandoSenao(_comandoSenao_);

    }

    @Override
    public Object clone()
    {
        return new AComandoSeSenaoCasadoComandoSeCasado(
            cloneNode(this._cmdSe_),
            cloneNode(this._parEsq_),
            cloneNode(this._ternarioExp_),
            cloneNode(this._parDir_),
            cloneNode(this._comandoSe_),
            cloneNode(this._cmdSenao_),
            cloneNode(this._comandoSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoSeSenaoCasadoComandoSeCasado(this);
    }

    public TCmdSe getCmdSe()
    {
        return this._cmdSe_;
    }

    public void setCmdSe(TCmdSe node)
    {
        if(this._cmdSe_ != null)
        {
            this._cmdSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmdSe_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PTernarioExp getTernarioExp()
    {
        return this._ternarioExp_;
    }

    public void setTernarioExp(PTernarioExp node)
    {
        if(this._ternarioExp_ != null)
        {
            this._ternarioExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ternarioExp_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PComandoSeCasado getComandoSe()
    {
        return this._comandoSe_;
    }

    public void setComandoSe(PComandoSeCasado node)
    {
        if(this._comandoSe_ != null)
        {
            this._comandoSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSe_ = node;
    }

    public TCmdSenao getCmdSenao()
    {
        return this._cmdSenao_;
    }

    public void setCmdSenao(TCmdSenao node)
    {
        if(this._cmdSenao_ != null)
        {
            this._cmdSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmdSenao_ = node;
    }

    public PComandoSeCasado getComandoSenao()
    {
        return this._comandoSenao_;
    }

    public void setComandoSenao(PComandoSeCasado node)
    {
        if(this._comandoSenao_ != null)
        {
            this._comandoSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cmdSe_)
            + toString(this._parEsq_)
            + toString(this._ternarioExp_)
            + toString(this._parDir_)
            + toString(this._comandoSe_)
            + toString(this._cmdSenao_)
            + toString(this._comandoSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cmdSe_ == child)
        {
            this._cmdSe_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._ternarioExp_ == child)
        {
            this._ternarioExp_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._comandoSe_ == child)
        {
            this._comandoSe_ = null;
            return;
        }

        if(this._cmdSenao_ == child)
        {
            this._cmdSenao_ = null;
            return;
        }

        if(this._comandoSenao_ == child)
        {
            this._comandoSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cmdSe_ == oldChild)
        {
            setCmdSe((TCmdSe) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._ternarioExp_ == oldChild)
        {
            setTernarioExp((PTernarioExp) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._comandoSe_ == oldChild)
        {
            setComandoSe((PComandoSeCasado) newChild);
            return;
        }

        if(this._cmdSenao_ == oldChild)
        {
            setCmdSenao((TCmdSenao) newChild);
            return;
        }

        if(this._comandoSenao_ == oldChild)
        {
            setComandoSenao((PComandoSeCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
