/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AComandoSeSenaoCasadoComandoSeCasado extends PComandoSeCasado
{
    private PExp _exp_;
    private PComandoSeCasado _comandoSe_;
    private PComandoSeCasado _comandoSenao_;

    public AComandoSeSenaoCasadoComandoSeCasado()
    {
        // Constructor
    }

    public AComandoSeSenaoCasadoComandoSeCasado(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PComandoSeCasado _comandoSe_,
        @SuppressWarnings("hiding") PComandoSeCasado _comandoSenao_)
    {
        // Constructor
        setExp(_exp_);

        setComandoSe(_comandoSe_);

        setComandoSenao(_comandoSenao_);

    }

    @Override
    public Object clone()
    {
        return new AComandoSeSenaoCasadoComandoSeCasado(
            cloneNode(this._exp_),
            cloneNode(this._comandoSe_),
            cloneNode(this._comandoSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoSeSenaoCasadoComandoSeCasado(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PComandoSeCasado getComandoSe()
    {
        return this._comandoSe_;
    }

    public void setComandoSe(PComandoSeCasado node)
    {
        if(this._comandoSe_ != null)
        {
            this._comandoSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSe_ = node;
    }

    public PComandoSeCasado getComandoSenao()
    {
        return this._comandoSenao_;
    }

    public void setComandoSenao(PComandoSeCasado node)
    {
        if(this._comandoSenao_ != null)
        {
            this._comandoSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._comandoSe_)
            + toString(this._comandoSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._comandoSe_ == child)
        {
            this._comandoSe_ = null;
            return;
        }

        if(this._comandoSenao_ == child)
        {
            this._comandoSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._comandoSe_ == oldChild)
        {
            setComandoSe((PComandoSeCasado) newChild);
            return;
        }

        if(this._comandoSenao_ == oldChild)
        {
            setComandoSenao((PComandoSeCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
