/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ACompOuExp extends PExp
{
    private PExp _exp_;
    private TCompOu _compOu_;
    private PPrio1 _prio1_;

    public ACompOuExp()
    {
        // Constructor
    }

    public ACompOuExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TCompOu _compOu_,
        @SuppressWarnings("hiding") PPrio1 _prio1_)
    {
        // Constructor
        setExp(_exp_);

        setCompOu(_compOu_);

        setPrio1(_prio1_);

    }

    @Override
    public Object clone()
    {
        return new ACompOuExp(
            cloneNode(this._exp_),
            cloneNode(this._compOu_),
            cloneNode(this._prio1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompOuExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TCompOu getCompOu()
    {
        return this._compOu_;
    }

    public void setCompOu(TCompOu node)
    {
        if(this._compOu_ != null)
        {
            this._compOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compOu_ = node;
    }

    public PPrio1 getPrio1()
    {
        return this._prio1_;
    }

    public void setPrio1(PPrio1 node)
    {
        if(this._prio1_ != null)
        {
            this._prio1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._compOu_)
            + toString(this._prio1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._compOu_ == child)
        {
            this._compOu_ = null;
            return;
        }

        if(this._prio1_ == child)
        {
            this._prio1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._compOu_ == oldChild)
        {
            setCompOu((TCompOu) newChild);
            return;
        }

        if(this._prio1_ == oldChild)
        {
            setPrio1((PPrio1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
