/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADivPrio5 extends PPrio5
{
    private PPrio5 _prio5_;
    private TDiv _div_;
    private PPrio6 _prio6_;

    public ADivPrio5()
    {
        // Constructor
    }

    public ADivPrio5(
        @SuppressWarnings("hiding") PPrio5 _prio5_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PPrio6 _prio6_)
    {
        // Constructor
        setPrio5(_prio5_);

        setDiv(_div_);

        setPrio6(_prio6_);

    }

    @Override
    public Object clone()
    {
        return new ADivPrio5(
            cloneNode(this._prio5_),
            cloneNode(this._div_),
            cloneNode(this._prio6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivPrio5(this);
    }

    public PPrio5 getPrio5()
    {
        return this._prio5_;
    }

    public void setPrio5(PPrio5 node)
    {
        if(this._prio5_ != null)
        {
            this._prio5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio5_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PPrio6 getPrio6()
    {
        return this._prio6_;
    }

    public void setPrio6(PPrio6 node)
    {
        if(this._prio6_ != null)
        {
            this._prio6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio5_)
            + toString(this._div_)
            + toString(this._prio6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio5_ == child)
        {
            this._prio5_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._prio6_ == child)
        {
            this._prio6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio5_ == oldChild)
        {
            setPrio5((PPrio5) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._prio6_ == oldChild)
        {
            setPrio6((PPrio6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
