/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AEnquantoComandoComandoSeSolteiro extends PComandoSeSolteiro
{
    private PExp _exp_;
    private PComandoSeSolteiro _comandoSeSolteiro_;

    public AEnquantoComandoComandoSeSolteiro()
    {
        // Constructor
    }

    public AEnquantoComandoComandoSeSolteiro(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PComandoSeSolteiro _comandoSeSolteiro_)
    {
        // Constructor
        setExp(_exp_);

        setComandoSeSolteiro(_comandoSeSolteiro_);

    }

    @Override
    public Object clone()
    {
        return new AEnquantoComandoComandoSeSolteiro(
            cloneNode(this._exp_),
            cloneNode(this._comandoSeSolteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnquantoComandoComandoSeSolteiro(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PComandoSeSolteiro getComandoSeSolteiro()
    {
        return this._comandoSeSolteiro_;
    }

    public void setComandoSeSolteiro(PComandoSeSolteiro node)
    {
        if(this._comandoSeSolteiro_ != null)
        {
            this._comandoSeSolteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSeSolteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._comandoSeSolteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._comandoSeSolteiro_ == child)
        {
            this._comandoSeSolteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._comandoSeSolteiro_ == oldChild)
        {
            setComandoSeSolteiro((PComandoSeSolteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
