/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AEnquantoComandoComandoSeSolteiro extends PComandoSeSolteiro
{
    private TCmdEnquanto _cmdEnquanto_;
    private TParEsq _parEsq_;
    private PTernarioExp _ternarioExp_;
    private TParDir _parDir_;
    private PComandoSeSolteiro _comandoSeSolteiro_;

    public AEnquantoComandoComandoSeSolteiro()
    {
        // Constructor
    }

    public AEnquantoComandoComandoSeSolteiro(
        @SuppressWarnings("hiding") TCmdEnquanto _cmdEnquanto_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PTernarioExp _ternarioExp_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PComandoSeSolteiro _comandoSeSolteiro_)
    {
        // Constructor
        setCmdEnquanto(_cmdEnquanto_);

        setParEsq(_parEsq_);

        setTernarioExp(_ternarioExp_);

        setParDir(_parDir_);

        setComandoSeSolteiro(_comandoSeSolteiro_);

    }

    @Override
    public Object clone()
    {
        return new AEnquantoComandoComandoSeSolteiro(
            cloneNode(this._cmdEnquanto_),
            cloneNode(this._parEsq_),
            cloneNode(this._ternarioExp_),
            cloneNode(this._parDir_),
            cloneNode(this._comandoSeSolteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnquantoComandoComandoSeSolteiro(this);
    }

    public TCmdEnquanto getCmdEnquanto()
    {
        return this._cmdEnquanto_;
    }

    public void setCmdEnquanto(TCmdEnquanto node)
    {
        if(this._cmdEnquanto_ != null)
        {
            this._cmdEnquanto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmdEnquanto_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PTernarioExp getTernarioExp()
    {
        return this._ternarioExp_;
    }

    public void setTernarioExp(PTernarioExp node)
    {
        if(this._ternarioExp_ != null)
        {
            this._ternarioExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ternarioExp_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PComandoSeSolteiro getComandoSeSolteiro()
    {
        return this._comandoSeSolteiro_;
    }

    public void setComandoSeSolteiro(PComandoSeSolteiro node)
    {
        if(this._comandoSeSolteiro_ != null)
        {
            this._comandoSeSolteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSeSolteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cmdEnquanto_)
            + toString(this._parEsq_)
            + toString(this._ternarioExp_)
            + toString(this._parDir_)
            + toString(this._comandoSeSolteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cmdEnquanto_ == child)
        {
            this._cmdEnquanto_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._ternarioExp_ == child)
        {
            this._ternarioExp_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._comandoSeSolteiro_ == child)
        {
            this._comandoSeSolteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cmdEnquanto_ == oldChild)
        {
            setCmdEnquanto((TCmdEnquanto) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._ternarioExp_ == oldChild)
        {
            setTernarioExp((PTernarioExp) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._comandoSeSolteiro_ == oldChild)
        {
            setComandoSeSolteiro((PComandoSeSolteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
