/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AIgualPrio2 extends PPrio2
{
    private PPrio2 _prio2_;
    private TIgual _igual_;
    private PPrio3 _prio3_;

    public AIgualPrio2()
    {
        // Constructor
    }

    public AIgualPrio2(
        @SuppressWarnings("hiding") PPrio2 _prio2_,
        @SuppressWarnings("hiding") TIgual _igual_,
        @SuppressWarnings("hiding") PPrio3 _prio3_)
    {
        // Constructor
        setPrio2(_prio2_);

        setIgual(_igual_);

        setPrio3(_prio3_);

    }

    @Override
    public Object clone()
    {
        return new AIgualPrio2(
            cloneNode(this._prio2_),
            cloneNode(this._igual_),
            cloneNode(this._prio3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualPrio2(this);
    }

    public PPrio2 getPrio2()
    {
        return this._prio2_;
    }

    public void setPrio2(PPrio2 node)
    {
        if(this._prio2_ != null)
        {
            this._prio2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio2_ = node;
    }

    public TIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(TIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    public PPrio3 getPrio3()
    {
        return this._prio3_;
    }

    public void setPrio3(PPrio3 node)
    {
        if(this._prio3_ != null)
        {
            this._prio3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio2_)
            + toString(this._igual_)
            + toString(this._prio3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio2_ == child)
        {
            this._prio2_ = null;
            return;
        }

        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        if(this._prio3_ == child)
        {
            this._prio3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio2_ == oldChild)
        {
            setPrio2((PPrio2) newChild);
            return;
        }

        if(this._igual_ == oldChild)
        {
            setIgual((TIgual) newChild);
            return;
        }

        if(this._prio3_ == oldChild)
        {
            setPrio3((PPrio3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
