/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorPrio3 extends PPrio3
{
    private PPrio3 _prio3_;
    private TMaior _maior_;
    private PPrio4 _prio4_;

    public AMaiorPrio3()
    {
        // Constructor
    }

    public AMaiorPrio3(
        @SuppressWarnings("hiding") PPrio3 _prio3_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PPrio4 _prio4_)
    {
        // Constructor
        setPrio3(_prio3_);

        setMaior(_maior_);

        setPrio4(_prio4_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorPrio3(
            cloneNode(this._prio3_),
            cloneNode(this._maior_),
            cloneNode(this._prio4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorPrio3(this);
    }

    public PPrio3 getPrio3()
    {
        return this._prio3_;
    }

    public void setPrio3(PPrio3 node)
    {
        if(this._prio3_ != null)
        {
            this._prio3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio3_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PPrio4 getPrio4()
    {
        return this._prio4_;
    }

    public void setPrio4(PPrio4 node)
    {
        if(this._prio4_ != null)
        {
            this._prio4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio3_)
            + toString(this._maior_)
            + toString(this._prio4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio3_ == child)
        {
            this._prio3_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._prio4_ == child)
        {
            this._prio4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio3_ == oldChild)
        {
            setPrio3((PPrio3) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._prio4_ == oldChild)
        {
            setPrio4((PPrio4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
