/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AMenosPrio4 extends PPrio4
{
    private PPrio4 _prio4_;
    private TMenos _menos_;
    private PPrio5 _prio5_;

    public AMenosPrio4()
    {
        // Constructor
    }

    public AMenosPrio4(
        @SuppressWarnings("hiding") PPrio4 _prio4_,
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PPrio5 _prio5_)
    {
        // Constructor
        setPrio4(_prio4_);

        setMenos(_menos_);

        setPrio5(_prio5_);

    }

    @Override
    public Object clone()
    {
        return new AMenosPrio4(
            cloneNode(this._prio4_),
            cloneNode(this._menos_),
            cloneNode(this._prio5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosPrio4(this);
    }

    public PPrio4 getPrio4()
    {
        return this._prio4_;
    }

    public void setPrio4(PPrio4 node)
    {
        if(this._prio4_ != null)
        {
            this._prio4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio4_ = node;
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PPrio5 getPrio5()
    {
        return this._prio5_;
    }

    public void setPrio5(PPrio5 node)
    {
        if(this._prio5_ != null)
        {
            this._prio5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio4_)
            + toString(this._menos_)
            + toString(this._prio5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio4_ == child)
        {
            this._prio4_ = null;
            return;
        }

        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._prio5_ == child)
        {
            this._prio5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio4_ == oldChild)
        {
            setPrio4((PPrio4) newChild);
            return;
        }

        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._prio5_ == oldChild)
        {
            setPrio5((PPrio5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
