/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AModPrio5 extends PPrio5
{
    private PPrio5 _prio5_;
    private TMod _mod_;
    private PPrio6 _prio6_;

    public AModPrio5()
    {
        // Constructor
    }

    public AModPrio5(
        @SuppressWarnings("hiding") PPrio5 _prio5_,
        @SuppressWarnings("hiding") TMod _mod_,
        @SuppressWarnings("hiding") PPrio6 _prio6_)
    {
        // Constructor
        setPrio5(_prio5_);

        setMod(_mod_);

        setPrio6(_prio6_);

    }

    @Override
    public Object clone()
    {
        return new AModPrio5(
            cloneNode(this._prio5_),
            cloneNode(this._mod_),
            cloneNode(this._prio6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModPrio5(this);
    }

    public PPrio5 getPrio5()
    {
        return this._prio5_;
    }

    public void setPrio5(PPrio5 node)
    {
        if(this._prio5_ != null)
        {
            this._prio5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio5_ = node;
    }

    public TMod getMod()
    {
        return this._mod_;
    }

    public void setMod(TMod node)
    {
        if(this._mod_ != null)
        {
            this._mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mod_ = node;
    }

    public PPrio6 getPrio6()
    {
        return this._prio6_;
    }

    public void setPrio6(PPrio6 node)
    {
        if(this._prio6_ != null)
        {
            this._prio6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio5_)
            + toString(this._mod_)
            + toString(this._prio6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio5_ == child)
        {
            this._prio5_ = null;
            return;
        }

        if(this._mod_ == child)
        {
            this._mod_ = null;
            return;
        }

        if(this._prio6_ == child)
        {
            this._prio6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio5_ == oldChild)
        {
            setPrio5((PPrio5) newChild);
            return;
        }

        if(this._mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        if(this._prio6_ == oldChild)
        {
            setPrio6((PPrio6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
