/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AMultPrio5 extends PPrio5
{
    private PPrio5 _prio5_;
    private TMult _mult_;
    private PPrio6 _prio6_;

    public AMultPrio5()
    {
        // Constructor
    }

    public AMultPrio5(
        @SuppressWarnings("hiding") PPrio5 _prio5_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PPrio6 _prio6_)
    {
        // Constructor
        setPrio5(_prio5_);

        setMult(_mult_);

        setPrio6(_prio6_);

    }

    @Override
    public Object clone()
    {
        return new AMultPrio5(
            cloneNode(this._prio5_),
            cloneNode(this._mult_),
            cloneNode(this._prio6_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultPrio5(this);
    }

    public PPrio5 getPrio5()
    {
        return this._prio5_;
    }

    public void setPrio5(PPrio5 node)
    {
        if(this._prio5_ != null)
        {
            this._prio5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio5_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PPrio6 getPrio6()
    {
        return this._prio6_;
    }

    public void setPrio6(PPrio6 node)
    {
        if(this._prio6_ != null)
        {
            this._prio6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio6_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio5_)
            + toString(this._mult_)
            + toString(this._prio6_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio5_ == child)
        {
            this._prio5_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._prio6_ == child)
        {
            this._prio6_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio5_ == oldChild)
        {
            setPrio5((PPrio5) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._prio6_ == oldChild)
        {
            setPrio6((PPrio6) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
