/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AParametroParametros extends PParametros
{
    private PParametro _parametro_;
    private final LinkedList<PBarraParametro> _barraParametro_ = new LinkedList<PBarraParametro>();

    public AParametroParametros()
    {
        // Constructor
    }

    public AParametroParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _barraParametro_)
    {
        // Constructor
        setParametro(_parametro_);

        setBarraParametro(_barraParametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametroParametros(
            cloneNode(this._parametro_),
            cloneList(this._barraParametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametroParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PBarraParametro> getBarraParametro()
    {
        return this._barraParametro_;
    }

    public void setBarraParametro(List<?> list)
    {
        for(PBarraParametro e : this._barraParametro_)
        {
            e.parent(null);
        }
        this._barraParametro_.clear();

        for(Object obj_e : list)
        {
            PBarraParametro e = (PBarraParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._barraParametro_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._barraParametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._barraParametro_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PBarraParametro> i = this._barraParametro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PBarraParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
