/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class APrio5Prio4 extends PPrio4
{
    private PPrio5 _prio5_;

    public APrio5Prio4()
    {
        // Constructor
    }

    public APrio5Prio4(
        @SuppressWarnings("hiding") PPrio5 _prio5_)
    {
        // Constructor
        setPrio5(_prio5_);

    }

    @Override
    public Object clone()
    {
        return new APrio5Prio4(
            cloneNode(this._prio5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrio5Prio4(this);
    }

    public PPrio5 getPrio5()
    {
        return this._prio5_;
    }

    public void setPrio5(PPrio5 node)
    {
        if(this._prio5_ != null)
        {
            this._prio5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio5_ == child)
        {
            this._prio5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio5_ == oldChild)
        {
            setPrio5((PPrio5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
