/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class APrio1Prio0 extends PPrio0
{
    private PPrio1 _prio1_;

    public APrio1Prio0()
    {
        // Constructor
    }

    public APrio1Prio0(
        @SuppressWarnings("hiding") PPrio1 _prio1_)
    {
        // Constructor
        setPrio1(_prio1_);

    }

    @Override
    public Object clone()
    {
        return new APrio1Prio0(
            cloneNode(this._prio1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrio1Prio0(this);
    }

    public PPrio1 getPrio1()
    {
        return this._prio1_;
    }

    public void setPrio1(PPrio1 node)
    {
        if(this._prio1_ != null)
        {
            this._prio1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio1_ == child)
        {
            this._prio1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio1_ == oldChild)
        {
            setPrio1((PPrio1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
