/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class APrio2Prio1 extends PPrio1
{
    private PPrio2 _prio2_;

    public APrio2Prio1()
    {
        // Constructor
    }

    public APrio2Prio1(
        @SuppressWarnings("hiding") PPrio2 _prio2_)
    {
        // Constructor
        setPrio2(_prio2_);

    }

    @Override
    public Object clone()
    {
        return new APrio2Prio1(
            cloneNode(this._prio2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrio2Prio1(this);
    }

    public PPrio2 getPrio2()
    {
        return this._prio2_;
    }

    public void setPrio2(PPrio2 node)
    {
        if(this._prio2_ != null)
        {
            this._prio2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio2_ == child)
        {
            this._prio2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio2_ == oldChild)
        {
            setPrio2((PPrio2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
