/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class APrio7Prio6 extends PPrio6
{
    private PPrio7 _prio7_;

    public APrio7Prio6()
    {
        // Constructor
    }

    public APrio7Prio6(
        @SuppressWarnings("hiding") PPrio7 _prio7_)
    {
        // Constructor
        setPrio7(_prio7_);

    }

    @Override
    public Object clone()
    {
        return new APrio7Prio6(
            cloneNode(this._prio7_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrio7Prio6(this);
    }

    public PPrio7 getPrio7()
    {
        return this._prio7_;
    }

    public void setPrio7(PPrio7 node)
    {
        if(this._prio7_ != null)
        {
            this._prio7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prio7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prio7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prio7_ == child)
        {
            this._prio7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prio7_ == oldChild)
        {
            setPrio7((PPrio7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
