/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AProdDecVarPrograma extends PPrograma
{
    private PProdDecVar _prodDecVar_;

    public AProdDecVarPrograma()
    {
        // Constructor
    }

    public AProdDecVarPrograma(
        @SuppressWarnings("hiding") PProdDecVar _prodDecVar_)
    {
        // Constructor
        setProdDecVar(_prodDecVar_);

    }

    @Override
    public Object clone()
    {
        return new AProdDecVarPrograma(
            cloneNode(this._prodDecVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProdDecVarPrograma(this);
    }

    public PProdDecVar getProdDecVar()
    {
        return this._prodDecVar_;
    }

    public void setProdDecVar(PProdDecVar node)
    {
        if(this._prodDecVar_ != null)
        {
            this._prodDecVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prodDecVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prodDecVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prodDecVar_ == child)
        {
            this._prodDecVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prodDecVar_ == oldChild)
        {
            setProdDecVar((PProdDecVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
