/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AProdDecConstPrograma extends PPrograma
{
    private PProdDecConst _prodDecConst_;

    public AProdDecConstPrograma()
    {
        // Constructor
    }

    public AProdDecConstPrograma(
        @SuppressWarnings("hiding") PProdDecConst _prodDecConst_)
    {
        // Constructor
        setProdDecConst(_prodDecConst_);

    }

    @Override
    public Object clone()
    {
        return new AProdDecConstPrograma(
            cloneNode(this._prodDecConst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProdDecConstPrograma(this);
    }

    public PProdDecConst getProdDecConst()
    {
        return this._prodDecConst_;
    }

    public void setProdDecConst(PProdDecConst node)
    {
        if(this._prodDecConst_ != null)
        {
            this._prodDecConst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prodDecConst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prodDecConst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prodDecConst_ == child)
        {
            this._prodDecConst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prodDecConst_ == oldChild)
        {
            setProdDecConst((PProdDecConst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
