/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TCompE extends Token
{
    public TCompE()
    {
        super.setText("e");
    }

    public TCompE(int line, int pos)
    {
        super.setText("e");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCompE(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCompE(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCompE text.");
    }
}
