/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.analysis;

import java.util.*;
import sarapatel.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgramaEntrada(AProgramaEntrada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdDeclVarProgramaEsq(AProdDeclVarProgramaEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdDeclConstProgramaEsq(AProdDeclConstProgramaEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdDeclProcedimentoProgramaDir(AProdDeclProcedimentoProgramaDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdDeclFuncaoProgramaDir(AProdDeclFuncaoProgramaDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarIdProdDeclVar(AVarIdProdDeclVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarIdAtribuicaoProdDeclVar(AVarIdAtribuicaoProdDeclVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstanteProdDeclConst(AConstanteProdDeclConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdAtribuicaoIdAtribuicao(AIdAtribuicaoIdAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoBaseTipo(ATipoBaseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoExpTipo(ATipoExpTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoInteiroTipoBase(ATipoInteiroTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoBooleanoTipoBase(ATipoBooleanoTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoRealTipoBase(ATipoRealTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoCadeiaTipoBase(ATipoCadeiaTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdDeclProcedimentoProdDeclProcedimento(AProdDeclProcedimentoProdDeclProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdDeclFuncaoProdDeclFuncao(AProdDeclFuncaoProdDeclFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroParametros(AParametroParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVazioParametros(AVazioParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABarraParametroBarraParametro(ABarraParametroBarraParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoParametroParametro(ATipoParametroParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoBaseTipoParametro(ATipoBaseTipoParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoParametroTipoParametro(ATipoParametroTipoParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSeSolteiroComandoSeSolteiro(AComandoSeSolteiroComandoSeSolteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSeSenaoSolteiroComandoSeSolteiro(AComandoSeSenaoSolteiroComandoSeSolteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoComandoComandoSeSolteiro(AEnquantoComandoComandoSeSolteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSeSenaoCasadoComandoSeCasado(AComandoSeSenaoCasadoComandoSeCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoComandoComandoSeCasado(AEnquantoComandoComandoSeCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdAtribuicaoComandoComandoSeCasado(AIdAtribuicaoComandoComandoSeCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaProcedimentoComandoComandoSeCasado(AChamadaProcedimentoComandoComandoSeCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComandosComandoSeCasado(ABlocoComandosComandoSeCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSeCasadoComando(AComandoSeCasadoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSeSolteiroComando(AComandoSeSolteiroComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComandosBlocoComandos(ABlocoComandosBlocoComandos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValorValor(AValorValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValorArrayValor(AValorArrayValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaChamadaProcedimento(AChamadaChamadaProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEExp(AEExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualExp(AIgualExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorIgualExp(AMaiorIgualExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorExp(AMaiorExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExp(ASomaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosExp(AMenosExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegacaoExp(ANegacaoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegativoExp(ANegativoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroIntExp(ANumeroIntExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroRealExp(ANumeroRealExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACadeiaExp(ACadeiaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVerdadeExp(AVerdadeExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFalsoExp(AFalsoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValorExp(AValorExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaFuncaoExp(AChamadaFuncaoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVazioExp(AVazioExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoExpressoesExp(ABlocoExpressoesExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrayCompExp(AArrayCompExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroInt(TNumeroInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroReal(TNumeroReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroBinario(TNumeroBinario node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDeclVar(TDeclVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDeclConst(TDeclConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDeclProcedimento(TDeclProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDeclFuncao(TDeclFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCmdSe(TCmdSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCmdSenao(TCmdSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCmdEnquanto(TCmdEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoInteiro(TTipoInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoBooleano(TTipoBooleano node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoReal(TTipoReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoCadeia(TTipoCadeia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInicioBloco(TInicioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFimBloco(TFimBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParEsq(TParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParDir(TParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColEsq(TColEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColDir(TColDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAbreComentario(TAbreComentario node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFechaComentario(TFechaComentario node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPartida(TPartida node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBarra(TBarra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNegacao(TNegacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCompE(TCompE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCompOu(TCompOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenos(TMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVerdade(TVerdade node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFalso(TFalso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVazio(TVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCadeia(TCadeia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioBloco(TComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
