/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.analysis;

import sarapatel.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTNumeroInt(TNumeroInt node);
    void caseTNumeroReal(TNumeroReal node);
    void caseTNumeroBinario(TNumeroBinario node);
    void caseTDeclVar(TDeclVar node);
    void caseTDeclConst(TDeclConst node);
    void caseTDeclProcedimento(TDeclProcedimento node);
    void caseTDeclFuncao(TDeclFuncao node);
    void caseTCmdSe(TCmdSe node);
    void caseTCmdSenao(TCmdSenao node);
    void caseTCmdEnquanto(TCmdEnquanto node);
    void caseTTipoInteiro(TTipoInteiro node);
    void caseTTipoBooleano(TTipoBooleano node);
    void caseTTipoReal(TTipoReal node);
    void caseTTipoCadeia(TTipoCadeia node);
    void caseTInicioBloco(TInicioBloco node);
    void caseTFimBloco(TFimBloco node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTColEsq(TColEsq node);
    void caseTColDir(TColDir node);
    void caseTAspasSimples(TAspasSimples node);
    void caseTAspasDupla(TAspasDupla node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTBarra(TBarra node);
    void caseTDoispontos(TDoispontos node);
    void caseTPontovirgula(TPontovirgula node);
    void caseTIgual(TIgual node);
    void caseTMaiorIgual(TMaiorIgual node);
    void caseTMaior(TMaior node);
    void caseTNegacao(TNegacao node);
    void caseTCompE(TCompE node);
    void caseTCompOu(TCompOu node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTVerdade(TVerdade node);
    void caseTFalso(TFalso node);
    void caseTVazio(TVazio node);
    void caseTCadeia(TCadeia node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseTId(TId node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
